import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "tr" | "en" | "de" | "ar" | "ru";

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // TopBar
    "topbar.language": "Dil Seçiniz",
    "topbar.appointment": "Randevu Sistemini Seviyoruz — ERSAN DİAMOND",
    "topbar.campaigns": "Kampanyalar",
    "topbar.help": "Yardım & Destek",
    // Header
    "header.search": "Ürün Ara",
    // CategoryNav
    "cat.bags": "ÇANTALAR",
    "cat.watches": "SAATLER",
    "cat.jewelry": "MÜCEVHER",
    "cat.brand_jewelry": "MARKA MÜCEVHER",
    "cat.hermes_bags": "Hermes Çantalar",
    "cat.chanel_bags": "Chanel Çantalar",
    "cat.louis_vuitton": "Louis Vuitton",
    "cat.all_bags": "Tüm Çantalar",
    "cat.rolex": "Rolex",
    "cat.patek": "Patek Philippe",
    "cat.ap": "Audemars Piguet",
    "cat.all_watches": "Tüm Saatler",
    "cat.necklace": "Kolye",
    "cat.ring": "Yüzük",
    "cat.bracelet": "Bileklik",
    "cat.all_jewelry": "Tüm Mücevherler",
    "cat.cartier": "Cartier",
    "cat.van_cleef": "Van Cleef",
    "cat.tiffany": "Tiffany",
    "cat.all_brand_jewelry": "Tüm Marka Mücevherler",
    "cat.contact": "Bize Ulaşın",
    // HeroSlider
    "hero.discover": "KEŞFET",
    // HeroCategories
    "herocat.bags": "ÇANTALAR",
    "herocat.watches": "SAATLER",
    "herocat.jewelry": "MÜCEVHERLER",
    // PopularCategories
    "popular.title": "Popüler Kategoriler",
    // BrandsSection
    "brands.title": "Markalar",
    "brands.view_all": "Tümünü Gör →",
    "brands.no_products": "Henüz ürün eklenmemiş.",
    "brands.shipping_sub": "Ersan Diamond",
    "brands.shipping_title": "Güvenli Kargo",
    "brands.shipping_desc": "Tüm ürünlerimiz özel sigortalı ve güvenli paketleme ile kapınıza kadar ulaştırılır.",
    // Footer
    "footer.categories": "KATEGORİLER",
    "footer.bags": "Çantalar",
    "footer.watches": "Saatler",
    "footer.jewelry": "Mücevherler",
    "footer.brand_jewelry": "Marka Mücevher",
    "footer.brands": "MARKALAR",
    "footer.info": "BİLGİ",
    "footer.contact": "Bize Ulaşın",
    "footer.campaigns": "Kampanyalar",
    "footer.terms": "Kullanım Koşulları",
    "footer.privacy": "Gizlilik Politikası",
    "footer.rights": "Tüm hakları saklıdır.",
    // Contact
    "contact.title": "Bize Ulaşın",
    "contact.subtitle": "Sorularınız veya talepleriniz için formu doldurun, en kısa sürede size dönüş yapalım.",
    "contact.name": "Ad Soyad *",
    "contact.name_placeholder": "Adınız ve soyadınız",
    "contact.email": "E-posta *",
    "contact.phone": "Telefon",
    "contact.message": "Mesajınız *",
    "contact.message_placeholder": "Mesajınızı buraya yazın...",
    "contact.send": "Gönder",
    "contact.sending": "Gönderiliyor...",
    "contact.error_title": "Hata",
    "contact.error_required": "Lütfen zorunlu alanları doldurun.",
    "contact.error_send": "Mesaj gönderilemedi. Lütfen tekrar deneyin.",
    "contact.success_title": "Başarılı",
    "contact.success_msg": "Mesajınız başarıyla gönderildi.",
    // ProductDetail
    "product.loading": "Yükleniyor...",
    "product.not_found": "Ürün Bulunamadı",
    "product.back_home": "Ana Sayfaya Dön",
    "product.home": "Ana Sayfa",
    "product.reviews": "değerlendirme",
    "product.whatsapp": "WHATSAPP İLE BİLGİ AL",
    "product.whatsapp_msg": "Merhaba, {brand} {name} ürünü hakkında bilgi almak ve satın almak istiyorum.",
    "product.favorite": "Favorilerime Ekle",
    "product.viewed_by": "ziyaretçi tarafından görüntülendi.",
    "product.shipping": "Sigortalı ve Hızlı Kargo",
    "product.certificate": "Orijinal Ürün Sertifikası",
    "product.safe_shopping": "Güvenli Alışveriş",
    "product.easy_exchange": "Kolay Değişim",
    "product.category_label": "Kategorisi:",
    "product.brand_label": "Marka:",
    "product.no_image": "Görsel Yok",
    // Category page
    "category.no_products": "Bu kategoride henüz ürün bulunmamaktadır.",
    "category.no_image": "Görsel Yok",
  },
  en: {
    "topbar.language": "Select Language",
    "topbar.appointment": "We Love the Appointment System — ERSAN DIAMOND",
    "topbar.campaigns": "Campaigns",
    "topbar.help": "Help & Support",
    "header.search": "Search Products",
    "cat.bags": "BAGS",
    "cat.watches": "WATCHES",
    "cat.jewelry": "JEWELRY",
    "cat.brand_jewelry": "BRAND JEWELRY",
    "cat.hermes_bags": "Hermes Bags",
    "cat.chanel_bags": "Chanel Bags",
    "cat.louis_vuitton": "Louis Vuitton",
    "cat.all_bags": "All Bags",
    "cat.rolex": "Rolex",
    "cat.patek": "Patek Philippe",
    "cat.ap": "Audemars Piguet",
    "cat.all_watches": "All Watches",
    "cat.necklace": "Necklaces",
    "cat.ring": "Rings",
    "cat.bracelet": "Bracelets",
    "cat.all_jewelry": "All Jewelry",
    "cat.cartier": "Cartier",
    "cat.van_cleef": "Van Cleef",
    "cat.tiffany": "Tiffany",
    "cat.all_brand_jewelry": "All Brand Jewelry",
    "cat.contact": "Contact Us",
    "hero.discover": "DISCOVER",
    "herocat.bags": "BAGS",
    "herocat.watches": "WATCHES",
    "herocat.jewelry": "JEWELRY",
    "popular.title": "Popular Categories",
    "brands.title": "Brands",
    "brands.view_all": "View All →",
    "brands.no_products": "No products added yet.",
    "brands.shipping_sub": "Ersan Diamond",
    "brands.shipping_title": "Secure Shipping",
    "brands.shipping_desc": "All our products are delivered to your door with special insurance and secure packaging.",
    "footer.categories": "CATEGORIES",
    "footer.bags": "Bags",
    "footer.watches": "Watches",
    "footer.jewelry": "Jewelry",
    "footer.brand_jewelry": "Brand Jewelry",
    "footer.brands": "BRANDS",
    "footer.info": "INFO",
    "footer.contact": "Contact Us",
    "footer.campaigns": "Campaigns",
    "footer.terms": "Terms of Use",
    "footer.privacy": "Privacy Policy",
    "footer.rights": "All rights reserved.",
    "contact.title": "Contact Us",
    "contact.subtitle": "Fill out the form with your questions or requests, and we'll get back to you as soon as possible.",
    "contact.name": "Full Name *",
    "contact.name_placeholder": "Your full name",
    "contact.email": "Email *",
    "contact.phone": "Phone",
    "contact.message": "Your Message *",
    "contact.message_placeholder": "Write your message here...",
    "contact.send": "Send",
    "contact.sending": "Sending...",
    "contact.error_title": "Error",
    "contact.error_required": "Please fill in the required fields.",
    "contact.error_send": "Message could not be sent. Please try again.",
    "contact.success_title": "Success",
    "contact.success_msg": "Your message has been sent successfully.",
    "product.loading": "Loading...",
    "product.not_found": "Product Not Found",
    "product.back_home": "Back to Home",
    "product.home": "Home",
    "product.reviews": "reviews",
    "product.whatsapp": "GET INFO VIA WHATSAPP",
    "product.whatsapp_msg": "Hello, I would like to get information about {brand} {name} and purchase it.",
    "product.favorite": "Add to Favorites",
    "product.viewed_by": "visitors viewed this product.",
    "product.shipping": "Insured & Fast Shipping",
    "product.certificate": "Original Product Certificate",
    "product.safe_shopping": "Safe Shopping",
    "product.easy_exchange": "Easy Exchange",
    "product.category_label": "Category:",
    "product.brand_label": "Brand:",
    "product.no_image": "No Image",
    "category.no_products": "No products found in this category yet.",
    "category.no_image": "No Image",
  },
  de: {
    "topbar.language": "Sprache wählen",
    "topbar.appointment": "Wir lieben das Terminsystem — ERSAN DIAMOND",
    "topbar.campaigns": "Kampagnen",
    "topbar.help": "Hilfe & Support",
    "header.search": "Produkte suchen",
    "cat.bags": "TASCHEN",
    "cat.watches": "UHREN",
    "cat.jewelry": "SCHMUCK",
    "cat.brand_jewelry": "MARKENSCHMUCK",
    "cat.hermes_bags": "Hermes Taschen",
    "cat.chanel_bags": "Chanel Taschen",
    "cat.louis_vuitton": "Louis Vuitton",
    "cat.all_bags": "Alle Taschen",
    "cat.rolex": "Rolex",
    "cat.patek": "Patek Philippe",
    "cat.ap": "Audemars Piguet",
    "cat.all_watches": "Alle Uhren",
    "cat.necklace": "Halsketten",
    "cat.ring": "Ringe",
    "cat.bracelet": "Armbänder",
    "cat.all_jewelry": "Aller Schmuck",
    "cat.cartier": "Cartier",
    "cat.van_cleef": "Van Cleef",
    "cat.tiffany": "Tiffany",
    "cat.all_brand_jewelry": "Aller Markenschmuck",
    "cat.contact": "Kontakt",
    "hero.discover": "ENTDECKEN",
    "herocat.bags": "TASCHEN",
    "herocat.watches": "UHREN",
    "herocat.jewelry": "SCHMUCK",
    "popular.title": "Beliebte Kategorien",
    "brands.title": "Marken",
    "brands.view_all": "Alle anzeigen →",
    "brands.no_products": "Noch keine Produkte hinzugefügt.",
    "brands.shipping_sub": "Ersan Diamond",
    "brands.shipping_title": "Sicherer Versand",
    "brands.shipping_desc": "Alle unsere Produkte werden mit Sonderversicherung und sicherer Verpackung an Ihre Tür geliefert.",
    "footer.categories": "KATEGORIEN",
    "footer.bags": "Taschen",
    "footer.watches": "Uhren",
    "footer.jewelry": "Schmuck",
    "footer.brand_jewelry": "Markenschmuck",
    "footer.brands": "MARKEN",
    "footer.info": "INFO",
    "footer.contact": "Kontakt",
    "footer.campaigns": "Kampagnen",
    "footer.terms": "Nutzungsbedingungen",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.rights": "Alle Rechte vorbehalten.",
    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Füllen Sie das Formular mit Ihren Fragen oder Anfragen aus, und wir werden uns so schnell wie möglich bei Ihnen melden.",
    "contact.name": "Vollständiger Name *",
    "contact.name_placeholder": "Ihr vollständiger Name",
    "contact.email": "E-Mail *",
    "contact.phone": "Telefon",
    "contact.message": "Ihre Nachricht *",
    "contact.message_placeholder": "Schreiben Sie Ihre Nachricht hier...",
    "contact.send": "Senden",
    "contact.sending": "Wird gesendet...",
    "contact.error_title": "Fehler",
    "contact.error_required": "Bitte füllen Sie die Pflichtfelder aus.",
    "contact.error_send": "Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut.",
    "contact.success_title": "Erfolg",
    "contact.success_msg": "Ihre Nachricht wurde erfolgreich gesendet.",
    "product.loading": "Wird geladen...",
    "product.not_found": "Produkt nicht gefunden",
    "product.back_home": "Zurück zur Startseite",
    "product.home": "Startseite",
    "product.reviews": "Bewertungen",
    "product.whatsapp": "INFO ÜBER WHATSAPP",
    "product.whatsapp_msg": "Hallo, ich möchte Informationen über {brand} {name} erhalten und es kaufen.",
    "product.favorite": "Zu Favoriten hinzufügen",
    "product.viewed_by": "Besucher haben dieses Produkt angesehen.",
    "product.shipping": "Versichert & Schneller Versand",
    "product.certificate": "Original-Produktzertifikat",
    "product.safe_shopping": "Sicheres Einkaufen",
    "product.easy_exchange": "Einfacher Umtausch",
    "product.category_label": "Kategorie:",
    "product.brand_label": "Marke:",
    "product.no_image": "Kein Bild",
    "category.no_products": "In dieser Kategorie wurden noch keine Produkte gefunden.",
    "category.no_image": "Kein Bild",
  },
  ar: {
    "topbar.language": "اختر اللغة",
    "topbar.appointment": "نحب نظام المواعيد — إرسان دايموند",
    "topbar.campaigns": "الحملات",
    "topbar.help": "المساعدة والدعم",
    "header.search": "البحث عن المنتجات",
    "cat.bags": "الحقائب",
    "cat.watches": "الساعات",
    "cat.jewelry": "المجوهرات",
    "cat.brand_jewelry": "مجوهرات الماركات",
    "cat.hermes_bags": "حقائب هيرمس",
    "cat.chanel_bags": "حقائب شانيل",
    "cat.louis_vuitton": "لويس فويتون",
    "cat.all_bags": "جميع الحقائب",
    "cat.rolex": "رولكس",
    "cat.patek": "باتيك فيليب",
    "cat.ap": "أوديمار بيغه",
    "cat.all_watches": "جميع الساعات",
    "cat.necklace": "القلائد",
    "cat.ring": "الخواتم",
    "cat.bracelet": "الأساور",
    "cat.all_jewelry": "جميع المجوهرات",
    "cat.cartier": "كارتييه",
    "cat.van_cleef": "فان كليف",
    "cat.tiffany": "تيفاني",
    "cat.all_brand_jewelry": "جميع مجوهرات الماركات",
    "cat.contact": "اتصل بنا",
    "hero.discover": "اكتشف",
    "herocat.bags": "الحقائب",
    "herocat.watches": "الساعات",
    "herocat.jewelry": "المجوهرات",
    "popular.title": "الفئات الشائعة",
    "brands.title": "العلامات التجارية",
    "brands.view_all": "عرض الكل →",
    "brands.no_products": "لم يتم إضافة منتجات بعد.",
    "brands.shipping_sub": "إرسان دايموند",
    "brands.shipping_title": "شحن آمن",
    "brands.shipping_desc": "يتم تسليم جميع منتجاتنا إلى باب منزلك بتأمين خاص وتغليف آمن.",
    "footer.categories": "الفئات",
    "footer.bags": "الحقائب",
    "footer.watches": "الساعات",
    "footer.jewelry": "المجوهرات",
    "footer.brand_jewelry": "مجوهرات الماركات",
    "footer.brands": "العلامات التجارية",
    "footer.info": "معلومات",
    "footer.contact": "اتصل بنا",
    "footer.campaigns": "الحملات",
    "footer.terms": "شروط الاستخدام",
    "footer.privacy": "سياسة الخصوصية",
    "footer.rights": "جميع الحقوق محفوظة.",
    "contact.title": "اتصل بنا",
    "contact.subtitle": "املأ النموذج بأسئلتك أو طلباتك، وسنعود إليك في أقرب وقت ممكن.",
    "contact.name": "الاسم الكامل *",
    "contact.name_placeholder": "اسمك الكامل",
    "contact.email": "البريد الإلكتروني *",
    "contact.phone": "الهاتف",
    "contact.message": "رسالتك *",
    "contact.message_placeholder": "اكتب رسالتك هنا...",
    "contact.send": "إرسال",
    "contact.sending": "جارٍ الإرسال...",
    "contact.error_title": "خطأ",
    "contact.error_required": "يرجى ملء الحقول المطلوبة.",
    "contact.error_send": "تعذر إرسال الرسالة. يرجى المحاولة مرة أخرى.",
    "contact.success_title": "نجاح",
    "contact.success_msg": "تم إرسال رسالتك بنجاح.",
    "product.loading": "جارٍ التحميل...",
    "product.not_found": "المنتج غير موجود",
    "product.back_home": "العودة إلى الصفحة الرئيسية",
    "product.home": "الصفحة الرئيسية",
    "product.reviews": "تقييمات",
    "product.whatsapp": "احصل على معلومات عبر واتساب",
    "product.whatsapp_msg": "مرحبًا، أود الحصول على معلومات حول {brand} {name} وشرائه.",
    "product.favorite": "أضف إلى المفضلة",
    "product.viewed_by": "زائر شاهد هذا المنتج.",
    "product.shipping": "شحن مؤمن وسريع",
    "product.certificate": "شهادة المنتج الأصلي",
    "product.safe_shopping": "تسوق آمن",
    "product.easy_exchange": "استبدال سهل",
    "product.category_label": "الفئة:",
    "product.brand_label": "العلامة التجارية:",
    "product.no_image": "لا توجد صورة",
    "category.no_products": "لم يتم العثور على منتجات في هذه الفئة بعد.",
    "category.no_image": "لا توجد صورة",
  },
  ru: {
    "topbar.language": "Выберите язык",
    "topbar.appointment": "Мы любим систему записи — ERSAN DIAMOND",
    "topbar.campaigns": "Акции",
    "topbar.help": "Помощь и поддержка",
    "header.search": "Поиск товаров",
    "cat.bags": "СУМКИ",
    "cat.watches": "ЧАСЫ",
    "cat.jewelry": "ЮВЕЛИРНЫЕ ИЗДЕЛИЯ",
    "cat.brand_jewelry": "БРЕНДОВЫЕ УКРАШЕНИЯ",
    "cat.hermes_bags": "Сумки Hermes",
    "cat.chanel_bags": "Сумки Chanel",
    "cat.louis_vuitton": "Louis Vuitton",
    "cat.all_bags": "Все сумки",
    "cat.rolex": "Rolex",
    "cat.patek": "Patek Philippe",
    "cat.ap": "Audemars Piguet",
    "cat.all_watches": "Все часы",
    "cat.necklace": "Ожерелья",
    "cat.ring": "Кольца",
    "cat.bracelet": "Браслеты",
    "cat.all_jewelry": "Все украшения",
    "cat.cartier": "Cartier",
    "cat.van_cleef": "Van Cleef",
    "cat.tiffany": "Tiffany",
    "cat.all_brand_jewelry": "Все брендовые украшения",
    "cat.contact": "Связаться с нами",
    "hero.discover": "ОТКРОЙТЕ",
    "herocat.bags": "СУМКИ",
    "herocat.watches": "ЧАСЫ",
    "herocat.jewelry": "УКРАШЕНИЯ",
    "popular.title": "Популярные категории",
    "brands.title": "Бренды",
    "brands.view_all": "Смотреть все →",
    "brands.no_products": "Товары ещё не добавлены.",
    "brands.shipping_sub": "Ersan Diamond",
    "brands.shipping_title": "Безопасная доставка",
    "brands.shipping_desc": "Все наши товары доставляются к вашей двери со специальной страховкой и безопасной упаковкой.",
    "footer.categories": "КАТЕГОРИИ",
    "footer.bags": "Сумки",
    "footer.watches": "Часы",
    "footer.jewelry": "Украшения",
    "footer.brand_jewelry": "Брендовые украшения",
    "footer.brands": "БРЕНДЫ",
    "footer.info": "ИНФОРМАЦИЯ",
    "footer.contact": "Связаться с нами",
    "footer.campaigns": "Акции",
    "footer.terms": "Условия использования",
    "footer.privacy": "Политика конфиденциальности",
    "footer.rights": "Все права защищены.",
    "contact.title": "Свяжитесь с нами",
    "contact.subtitle": "Заполните форму с вашими вопросами или запросами, и мы свяжемся с вами как можно скорее.",
    "contact.name": "Полное имя *",
    "contact.name_placeholder": "Ваше полное имя",
    "contact.email": "Эл. почта *",
    "contact.phone": "Телефон",
    "contact.message": "Ваше сообщение *",
    "contact.message_placeholder": "Напишите ваше сообщение здесь...",
    "contact.send": "Отправить",
    "contact.sending": "Отправка...",
    "contact.error_title": "Ошибка",
    "contact.error_required": "Пожалуйста, заполните обязательные поля.",
    "contact.error_send": "Сообщение не удалось отправить. Пожалуйста, попробуйте снова.",
    "contact.success_title": "Успех",
    "contact.success_msg": "Ваше сообщение успешно отправлено.",
    "product.loading": "Загрузка...",
    "product.not_found": "Товар не найден",
    "product.back_home": "Вернуться на главную",
    "product.home": "Главная",
    "product.reviews": "отзывов",
    "product.whatsapp": "ПОЛУЧИТЬ ИНФОРМАЦИЮ В WHATSAPP",
    "product.whatsapp_msg": "Здравствуйте, я хотел бы получить информацию о {brand} {name} и купить его.",
    "product.favorite": "Добавить в избранное",
    "product.viewed_by": "посетителей просмотрели этот товар.",
    "product.shipping": "Застрахованная и быстрая доставка",
    "product.certificate": "Сертификат оригинального товара",
    "product.safe_shopping": "Безопасные покупки",
    "product.easy_exchange": "Лёгкий обмен",
    "product.category_label": "Категория:",
    "product.brand_label": "Бренд:",
    "product.no_image": "Нет изображения",
    "category.no_products": "В этой категории пока нет товаров.",
    "category.no_image": "Нет изображения",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "tr",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem("ersan-lang");
    return (stored as Language) || "tr";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("ersan-lang", lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language]?.[key] || translations.tr[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
